version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_cms_am
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    restart: always

  minio_setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin &&
      mc mb minio/media &&
      mc policy set public minio/media
      "

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure --verbosity=3
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      - DB_NAME=django_cms_am
      - DB_USER=postgres
      - DB_PASSWORD=toor
      - DB_HOST=db
      - DB_PORT=5432
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=media
      - AWS_S3_ENDPOINT_URL=http://minio:9000
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
  staticfiles:
  minio_data:
